services:
  storybook:
    build:
      context: ./test-storybook
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mcp-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - TEST_STORYBOOK_URL=http://storybook:6006
      - TEST_OUTPUT_DIR=/screenshots
      - DEBUG=true
    depends_on:
      storybook:
        condition: service_healthy
    volumes:
      - ./test-output:/screenshots
    # Run the tests instead of the server
    command: node tests/run-tests.js